spring:
  profiles:
    active: dev
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true

server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

mybatis-plus:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com.hualala.mapper: DEBUG
