spring:
  datasource:
    username: root
    password: mysql@TXY
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://62.234.24.11:3306/wechat?serverTimeZone=Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
  redis:
    host: 127.0.0.1
    port: 6379
    database: 1
    timeout: 10000

logging:
  config: classpath:log4j2-www.xml

wechat:
  appID: wx0abd83b135ccb8e5
  secret: 9a5eb79bb7f4f89a6d15eef2a2601c09
  token: WX_DESIGN_TOKEN
  encodingAESKey: PJKtnHu74965O2WOfdxQgI3FOXrxrXd9YssgsaumzIW
  expire: 5000
  mchId: 1547520731
  mchKey: 04b19705b97f4d07bf57f4f455438d2d

curator:
  retryCount: 5  #重试次数
  elapsedTimeMs: 5000   #重试间隔时间
  connectString: 127.0.0.1:2181,127.0.0.1:3181,127.0.0.1:4181   # zookeeper 地址
  sessionTimeoutMs: 60000 # session超时时间
  connectionTimeoutMs: 5000  # 连接超时时间