spring:
  profiles:
    active: dev
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true
  freemarker:
    suffix: .ftl                                 # 设置模板后缀名
    content-type: text/html                      # 设置文档类型
    charset: UTF-8                               # 设置页面编码格式
    cache: false                                 # 设置页面缓存
    template-loader-path: classpath:/templates   # 设置ftl文件路径
    mvc:
      static-path-pattern: /static         # 设置静态文件路径，js,css等
  mail:
    host: smtp.163.com
    username: qingshangaochuang@163.com
    password: 92CB3F75188C6DDF
    default-encoding: UTF-8
    toUser:
      - 918968972@qq.com
      - 705366435@qq.com

server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

mybatis-plus:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml

cos:
  secretID: AKIDvmPp0vr00sVt2wNyBF4dw0qSvCIB8Iah
  secretKey: 73lHm5B3jCSVLvFI6sPffQyLVTCNIyQc
  region: ap-beijing
  bucket: wechat-design-1257895402
  server: https://wechat-design-1257895402.cos.ap-beijing.myqcloud.com/