spring:
  profiles:
    active: dev
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true
  freemarker:
    suffix: .ftl                                 # 设置模板后缀名
    content-type: text/html                      # 设置文档类型
    charset: UTF-8                               # 设置页面编码格式
    cache: false                                 # 设置页面缓存
    template-loader-path: classpath:/templates   # 设置ftl文件路径
    mvc:
      static-path-pattern: /static         # 设置静态文件路径，js,css等
  mail:
    host: smtp.163.com
    username: qingshangaochuang@163.com
    password: 92CB3F75188C6DDF
    default-encoding: UTF-8
    toUser: 918968972@qq.com,705366435@qq.com
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false

server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
  compression:
    enabled: true
    mimeTypes: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css

mybatis-plus:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com.hualala.article: debug
    com.hualala.customer: debug
    com.hualala.pay: debug
    com.hualala.user: debug
    com.hualala.account: debug

wechat:
  appID: wx0abd83b135ccb8e5
  secret: 9a5eb79bb7f4f89a6d15eef2a2601c09
  token: WX_DESIGN_TOKEN
  encodingAESKey: PJKtnHu74965O2WOfdxQgI3FOXrxrXd9YssgsaumzIW
  expire: 5000

pay:
  mchId: 1547520731
  mchKey: 04b19705b97f4d07bf57f4f455438d2d

cos:
  secretID: AKIDvmPp0vr00sVt2wNyBF4dw0qSvCIB8Iah
  secretKey: 73lHm5B3jCSVLvFI6sPffQyLVTCNIyQc
  region: ap-beijing
  bucket: wechat-design-1257895402
  server: https://wechat-design-1257895402.cos.ap-beijing.myqcloud.com/

curator:
  retryCount: 5  #重试次数
  elapsedTimeMs: 5000   #重试间隔时间
  connectString: 127.0.0.1:2181,127.0.0.1:3181,127.0.0.1:4181   # zookeeper 地址
  sessionTimeoutMs: 60000 # session超时时间
  connectionTimeoutMs: 5000  # 连接超时时间