spring:
  datasource:
    username: root
    password: mysql@TXY
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://62.234.24.11:3306/wechat?serverTimeZone=Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
  redis:
    host: 127.0.0.1
    port: 6379
    database: 1
    timeout: 10000

logging:
  config: classpath:log4j2-www.xml



