server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

spring:
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/vote?serverTimeZone=Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
  redis:
    port:
    host:
    database: 0
    timeout: 10000
    jedis:
      max-active: 20
      max-wait: 10000
      min-idle: 5
      max-idle: 10

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com.hualala.mapper: DEBUG

wechat:
  appID: wx0abd83b135ccb8e5
  secret: 9a5eb79bb7f4f89a6d15eef2a2601c09
  token: WX_DESIGN_TOKEN
  encodingAESKey:
