spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/wechat?serverTimeZone=Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 10000

logging:
  config: classpath:log4j2-www.xml

wechat:
  appID:
  secret:
  token:
  encodingAESKey:
  expire: 5000

ai:
  apiKey: 7d14fa4bc295404a9fced576c37453e5